### ISSUE TITLE
Multilevel compound node expansion with cytoscape-expand-collapse breaks with cytoscape.js version >3.3.6

### ISSUE THREAD

**Issue by utkarshagarwal01** [iVis-at-Bilkent/cytoscape.js-expand-collapse#69] opened 2019-03-18 08:38 UTC
**Issue type**

Bug report

Cytoscape.js version : >3.3.6
Cytoscape Expand collpase version : 3.1.2
Node.js version : v10.15.0

**Current (buggy) behaviour**

When we expand a collapsed node having another collapsed node inside it, the code goes into an infinite while loop. The graph stops responding.

**Desired behaviour**

Not hang up and expand the node, please.

CodePen reproducing the issue:
https://codepen.io/utkarsh-agarwal/pen/ZPrbzq

**Comment by hasanbalci** [comment] 2019-03-18 11:25
Thanks for reporting, we will look into this issue before the next release.

**Comment by utkarshagarwal01** [comment] 2019-03-18 12:11
No problem @hasanbalci 
I have also identified the infinite loop that the code runs into: 
https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/8a2e4157def5613e0e477e393dc2c0720e41c032/src/expandCollapseUtilities.js#L606

**Comment by Remimstr** [comment] 2019-03-18 20:03
@utkarshagarwal01 I discovered this bug a couple of days ago and spent a number of hours trying to figure out what was causing it. Just out of curiosity, how you figured out it was that loop, I clearly did not know how to properly debug it.

**Comment by maxkfranz** [comment] 2019-03-19 02:53
I identified the same line as part of the issue. I’m not familiar with this extension’s code, but that particular line doesn’t make sense to me. 

You can’t query a removed element’s topology. That doesn’t generally make sense.  You could store the value in the scratchpad before removal, though. 

Additionally, the loop fails because it gets an empty collection. This isn’t checked in the loop, and the current node might be an orphan, right?  Once you have an empty collection, its parent is also always going to be empty.  

If you do find a bug in the core lib, please extract a minimal test case that can be used to verify and test a patch.

**Comment by maxkfranz** [comment] 2019-03-19 02:55
Note: If you have an infinite loop, you can just hit the pause button in the debugger after waiting a bit. You’ll break within the loop.

**Comment by kinimesi** [comment] 2019-03-19 17:31
Prior to v3.4.0, we could access the parent of a removed node by using `removedEle.parent()`. But in v3.4.0, when a node is removed its parent is set to `null` That is why we never get out of the while loop.
https://github.com/cytoscape/cytoscape.js/commit/7f5b63c2483988dcc0671b500458cee0c52f3d19#diff-0a12ab28e95ef60c35904eebf53d64e7R632

I think we can get the parent node from the `parent` field of data. When [this line](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/8a2e4157def5613e0e477e393dc2c0720e41c032/src/expandCollapseUtilities.js#L607) is replaced with the following line, it works both in newer and older versions (I haven't tested it extensively):
```
 current = cy.getElementById(current.data('parent'));
```
Assuming that `getElementById` is a constant time operation, this should not affect the performance.

**Comment by maxkfranz** [comment] 2019-03-19 18:33
`getElementById()` should be fine (map lookup).  This extension is a UI, so performance doesn't matter so much.  A user isn't going to click to toggle many nodes really quickly.

For something where performance matters a lot, you should cache the parent under scratch.

**Comment by maxkfranz** [comment] 2019-03-19 18:42
Note: It says in the docs not to use a removed node for anything other than keeping a reference to restore later: http://js.cytoscape.org/#cy.remove

So if code relies on behaviour of removed elements, then that code is relying on undefined behaviour.  The only methods that *could* be safe would be independent, read-only state within element JSON, like `ele.data()` or `ele.id()`.

**Comment by kinimesi** [comment] 2019-03-19 20:03
@maxkfranz the extension provides an API. With the API multiple nodes can be expanded/collapsed at once (for example in Newt, we have `Expand/Collapse All` options). During expand/collapse some computationally heavy tasks are performed (depending on extension options). In fact, when there are many nested nodes, expanding/collapsing all nodes recursively can take a while. So, performance matters.

**Comment by Rishi0405** [comment] 2019-05-02 14:26
Hi,

Is this issue resolved? After a few expand and collapse I'm facing this issue
http://jsfiddle.net/Rishi0405/3o5jq2zd/66/

Thanks,
Rishi

**Comment by hasanbalci** [comment] 2019-05-02 14:39
@Rishi0405 It is solved in the unstable branch, but a new version that include the fix hasn't been released yet.

**Comment by Rishi0405** [comment] 2019-05-03 08:56
@hasanbalci Thanks for the reply. I am waiting for the release :)

**Comment by Rishi0405** [comment] 2019-05-14 13:53
@hasanbalci I just checked the fix #69, commit 4b94483. I tried it locally and it is not working. Am I doing anything wrong? Please, I need some help.

**Comment by hasanbalci** [comment] 2019-05-17 08:56
It seems that commit 4b9448378271a859b8756ec6276a04db1dd9d628 cannot handle all cases. For example [here](http://jsfiddle.net/Ljtd6srx/), if we collapse first node n2 and then node n3, I think it gets stuck in the same while loop.

**Comment by mwdchang** [comment] 2019-07-25 15:24
We are running into this problem as well after upgrading to cytoscape 3.8. 

Has there been any progress at solving the multi-level expand issue at the plugin level?

**Comment by hasanbalci** [comment] 2019-07-25 18:01
@mwdchang Can you try the unstable branch? With the latest fix, now it must be working without problem. If it is ok, we will make a new release.

**Comment by hasanbalci** [comment] 2019-07-25 18:06
@utkarshagarwal01 @Rishi0405 Could you also please test the unstable branch to verify the problem is solved?

**Comment by mwdchang** [comment] 2019-07-25 19:17
@hasanbalci the fix on unstable branch is working for us. Thanks for the quick turn around!

**Comment by hasanbalci** [comment] 2019-07-26 11:51
I made another fix to consider nodes added later on.

**Comment by hasanbalci** [comment] 2019-07-30 11:42
This issue is solved in the unstable branch. It will be effective with the new release, so closing.

**Closed by hasanbalci** 2019-07-30 11:42 UTC

**Comment by utkarshagarwal01** [comment] 2019-08-09 05:41
@hasanbalci Yes, the problem is solved for me now.

**Comment by solemnify** [comment] 2019-08-22 05:15
@hasanbalci @kinimesi Is there any way we can get a new release with this fix please?

**Comment by shiv-veerashetty** [comment] 2019-12-13 11:11
which release has this fix ?

**Comment by ugurdogrusoz** [comment] 2019-12-13 11:13
@shiv-veerashetty Use the latest: https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/releases/tag/3.2.0

**Comment by shiv-veerashetty** [comment] 2019-12-13 11:55
@ugurdogrusoz  still facing the same issue ... work well with cytoscape@3.3.6 though

**Comment by hasanbalci** [comment] 2019-12-13 12:15
@shiv-veerashetty This issue must have been solved with cytoscape-expand-collapse v.3.2.0. Can you please provide a reproducible test case? You can use [jsfiddle](https://jsfiddle.net) or [jsbin](https://jsbin.com/?html,css,js,output) to easily provide a code sample.

**Comment by shiv-veerashetty** [comment] 2019-12-16 13:14
@hasanbalci @ugurdogrusoz I have created a fiddle and it seems to be working fine !!! in vue application still i am getting the same issue. Debugging further, i will keep you guys posted with the progress.

Quick query ... Does fcose work with bounding box ?? Basically what i wan to achieve is to have two bounding box with different layouts. May be fcose & preset (defined positions). Any pointers in this regard will be of great help !!
