### ISSUE TITLE
Expand collapse edges

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#94] opened 2020-04-06 08:58 UTC
When there are multiple edges between the same pair of nodes, we end up with either not easily seen set of edges or end up with expensive calculations of these edges (e.g. Bezier curves). So, let's allow a similar functionality for edges in this extension. The user should be able to specify whether all edges between a pair of nodes are to be collapsed into a single meta edge or only edges of the same type to a corresponding meta edge.
We should update the demos to reflect this new feature.

**Comment by ugurdogrusoz** [comment] 2020-04-14 06:34
Improvement suggestions with current partial implementation:
- When an edge doesn't have any type information in the field expected, assume it of a default / unknown type
- Get rid of redundancy in API
- When a collapse is performed and a new meta edge is created, its class should be similarly named as 'cy-expand-collapse-collapsed-edge'.
- When a collapse is performed and a new meta edge is created, this meta edge should have a field for direction of edges collapsed. If the input to the collapse function was:
  - a pair of nodes A and B: if all edges are from A to B, direction should be 'source-to-target'. if all edges are from B to A, it should be 'target-to-source'; otherwise, it should be 'bidirectional'.
  - a list of edges: assume the source and target of the first edge (from A to B) and do accordingly.
The demo should put an arrow head according to this field.
- Let's do one demo with undo/redo and:
  - Make sure the demo is nicely styled, paying attention to upper-lower case, etc.
  - Use pale colors for edges
  - Use consistent and bright color for selected nodes and edges

**Comment by nasimsaleh** [comment] 2020-04-20 08:52
@ugurdogrusoz point 11 cannot be handled in the extension level. I handled as much as possible in the demo level to keep it simple. But it is hard to know whether a function like 'collapseAll' would do any work or not because much processing is needed, grouping, counting edges etc.

**Comment by hasanbalci** [comment] 2020-04-20 17:17
I also encountered with missing edges after some undo-redo operations. Minimum steps I found to reproduce:
- Select at least two edges where each edge is between different node pairs.
- Click on "Collapse selected edges" and nothing happens. 
- Apply undo, nothing happens again.
- Apply redo, edges disappear.

Suggestions for README: 
- In new api functions, we can use `options` instead of `opts` as parameter to be consistent with the already existing functions. `api.collapseEdges(edges,opts)` -> `api.collapseEdges(edges, options)`
- In Elements Style section, in bullet 4, instead of "this edges", either "this edge" or "these edges" in two places.

**Comment by nasimsaleh** [comment] 2020-04-21 09:55
@hasanbalci  Could you please check?

**Comment by hasanbalci** [comment] 2020-04-21 11:37
@nasimsaleh The scenario I described above seems to be fixed, but in a different scenario I encountered with missing edge again: 

![MissingEdge](https://user-images.githubusercontent.com/22586369/79861341-ef5b4000-83dc-11ea-9020-aed3394b3a1c.gif)

After clicking on "Expand selected edges", I apply undo and redo, and edge disapperar.

**Comment by hasanbalci** [comment] 2020-04-21 12:05
@nasimsaleh I was also testing with cytoscape.js v3.3.0 and all three expand functionalities give error in the console.

**Comment by nasimsaleh** [comment] 2020-04-22 07:01
@hasanbalci  Could you check again now?

**Comment by hasanbalci** [comment] 2020-04-22 08:02
@nasimsaleh It seems that the bugs I mentioned are fixed now. Thanks!

**Closed** 2020-04-22 13:45 UTC
Labels: feature
