### ISSUE TITLE
Selecting collapsed nodes

### ISSUE THREAD

**Issue by asangalli** [iVis-at-Bilkent/cytoscape.js-expand-collapse#26] opened 2017-01-31 22:42 UTC
Hi,   I’ trying to build a Petri Net with Cytoscape.js, using Dagre.js layout and compound nodes for representing places witch in turns are subnets. 
I foud very useful using Expand-Collapse extension, starting with an overall collapsed network.  As the net evolve, I’d need to update some data on every node,  including children of collapsed nodes witch users may decide to expand or not.
 
Here is the issue: I’ not able using Cytoscape selectors, say cy.nodes() for example,  to select nodes inside collapsed ones. They seem not exist until node is expanded.  I’ m new to the world of Cytoscape and probably  this is the correct way to manage collapsed nodes but I can’t find a better solution to my problem. Any suggestion ? 
Thanks

**Comment by ugurdogrusoz** [comment] 2017-06-13 06:50
@metincansiper this should be straightforward right?
@asangalli Dagre layout won't respect compound nodes. I suggest you use cose-bilkent layout.

**Comment by metincansiper** [comment] 2017-06-20 09:15
@asangalli The children of collapsed nodes are removed, so you cannot access them through ```cy.nodes()```. However, I just exposed a getter function for the (removed) children of collapsed nodes. You can check ```getCollapsedChildren(node)``` from "https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse#api". Note that it returns both edges and nodes.

**Comment by ugurdogrusoz** [comment] 2019-06-17 11:53
@hasanbalci Could you verify the exposed API and close please?

**Comment by hasanbalci** [comment] 2019-06-17 12:08
Exposed API works as intended, so I am closing.

**Closed by hasanbalci** 2019-06-17 12:08 UTC
